image: haskell:latest

before_script:
  - apt-get update && apt-get install xz-utils make
  - cabal update

build:
  cache:
    paths:
      - _cache
      - dist-newstyle
  script:
    - cabal new-run blog build
  except:
    - master

pages:
  cache:
    paths:
      - _cache
      - dist-newstyle
  script:
    - cabal new-run blog build
  artifacts:
    paths:
      - _site
  only:
    - master
