image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r _site/* public
    - find public -type f -regex '.*\.\(html\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - pages
